name: Generate Snake

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: eather0056
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Commit and push the generated SVG to the 'output' branch
      - name: Commit and push changes
        run: |
          git switch --create output
          git add .
          git config --global user.email "mdeather0056@gmail.com"
          git config --global user.name "Your Name"
          git commit -m "Generate SVG snake graph" -a || echo "No changes to commit"
          git push origin output --force

# Note: Removed the 'github-push-action' and 'ghaction-github-pages' as we're using a simple script to push changes now.
